### ISSUE TITLE
in-description roll formulas don't work in FVTT 0.4.x

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#60]
rolling a spell card which has a roll formula won't be clickable because of `html.find is not a function` error.
